name: Continuous Integration

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      DISPLAY: :1

    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.5
    - name: Install and start Metacity window manager
      run: |
        sudo apt-get update
        sudo apt-get install xvfb metacity libwebkit2gtk-4.0-37
        Xvfb :1 &
        sleep 5
        metacity --sm-disable --replace 2> metacity.err &
    - name: Build with Maven
      run: mvn clean verify
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: Build artifacts
        path: |
          **/screenshots/*.jpeg
          **/target/**/*.log
          **/hs_err_pid*.log
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: Test results
        path: |
          */target/surefire-reports/*.xml
